language: node_js
node_js:
  - node
  - 5

cache:
  directories:
    - node_modules

before_install:
- cp .env.example .env

after_success:
  - 'npm run coveralls'
  - codecov

notifications:
  email:
    on_success: never
